// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using codegather.Persistance;

#nullable disable

namespace codegather.Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240211114457_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("codegather.Domain.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Competitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2024, 2, 11, 14, 44, 57, 392, DateTimeKind.Local).AddTicks(4408),
                            Description = "Eos velit reiciendis. Incidunt facilis assumenda velit. Reiciendis beatae necessitatibus illum qui qui perspiciatis nisi et debitis. Est qui dignissimos ipsam qui perspiciatis. Corrupti ex qui qui doloremque impedit voluptatum omnis iste. Ipsa eos est et numquam quaerat fugit quasi.",
                            EndTime = new DateTime(2024, 2, 18, 14, 44, 57, 392, DateTimeKind.Local).AddTicks(4834),
                            IsDeleted = false,
                            StartTime = new DateTime(2024, 2, 11, 14, 44, 57, 392, DateTimeKind.Local).AddTicks(4830),
                            Title = "Nulla nihil."
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2024, 2, 11, 14, 44, 57, 392, DateTimeKind.Local).AddTicks(4842),
                            Description = "Neque quisquam enim fugiat labore omnis. Autem doloribus magni aut nihil. Aut vitae quasi consequatur laudantium vel sint alias laborum. Praesentium qui itaque et earum et perferendis iusto. Officiis commodi rem. Omnis aspernatur dolorum sit.",
                            EndTime = new DateTime(2024, 2, 18, 14, 44, 57, 392, DateTimeKind.Local).AddTicks(5011),
                            IsDeleted = false,
                            StartTime = new DateTime(2024, 2, 11, 14, 44, 57, 392, DateTimeKind.Local).AddTicks(5010),
                            Title = "Deleniti illo."
                        });
                });

            modelBuilder.Entity("codegather.Domain.Metrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CompileTime")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<float>("MemoryUsage")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Metrics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompileTime = 0.5f,
                            CreatedTime = new DateTime(2024, 2, 11, 14, 44, 57, 395, DateTimeKind.Local).AddTicks(160),
                            IsDeleted = false,
                            MemoryUsage = 0.5f
                        },
                        new
                        {
                            Id = 2,
                            CompileTime = 0.5f,
                            CreatedTime = new DateTime(2024, 2, 11, 14, 44, 57, 395, DateTimeKind.Local).AddTicks(189),
                            IsDeleted = false,
                            MemoryUsage = 0.5f
                        },
                        new
                        {
                            Id = 3,
                            CompileTime = 0.5f,
                            CreatedTime = new DateTime(2024, 2, 11, 14, 44, 57, 395, DateTimeKind.Local).AddTicks(192),
                            IsDeleted = false,
                            MemoryUsage = 0.5f
                        },
                        new
                        {
                            Id = 4,
                            CompileTime = 0.5f,
                            CreatedTime = new DateTime(2024, 2, 11, 14, 44, 57, 395, DateTimeKind.Local).AddTicks(194),
                            IsDeleted = false,
                            MemoryUsage = 0.5f
                        });
                });

            modelBuilder.Entity("codegather.Domain.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestCases")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompetitionId = 1,
                            CreatedTime = new DateTime(2024, 2, 11, 14, 44, 57, 397, DateTimeKind.Local).AddTicks(5743),
                            Description = "Ut esse aut perferendis deserunt nulla commodi. Maiores omnis adipisci placeat quia dolorem et excepturi vel. Sapiente error hic cumque quod vero voluptatem nesciunt. Odit culpa itaque fugit rerum dolor.",
                            IsDeleted = false,
                            TestCases = "Test case 1, Test case 2, Test case 3"
                        },
                        new
                        {
                            Id = 2,
                            CompetitionId = 1,
                            CreatedTime = new DateTime(2024, 2, 11, 14, 44, 57, 397, DateTimeKind.Local).AddTicks(6028),
                            Description = "Culpa ipsum eum. Culpa aut iusto. Dolore itaque et explicabo.",
                            IsDeleted = false,
                            TestCases = "Test case 1, Test case 2, Test case 3"
                        },
                        new
                        {
                            Id = 3,
                            CompetitionId = 2,
                            CreatedTime = new DateTime(2024, 2, 11, 14, 44, 57, 397, DateTimeKind.Local).AddTicks(6127),
                            Description = "Quisquam consectetur at aut consectetur est aspernatur deleniti id dicta. Officia nesciunt unde mollitia qui perferendis. Excepturi quam sit et.",
                            IsDeleted = false,
                            TestCases = "Test case 1, Test case 2, Test case 3"
                        },
                        new
                        {
                            Id = 4,
                            CompetitionId = 2,
                            CreatedTime = new DateTime(2024, 2, 11, 14, 44, 57, 397, DateTimeKind.Local).AddTicks(6215),
                            Description = "Magnam architecto quae dolore reprehenderit. Repellat quam possimus. Ab vitae autem et ea molestias accusamus consequatur velit ducimus.",
                            IsDeleted = false,
                            TestCases = "Test case 1, Test case 2, Test case 3"
                        });
                });

            modelBuilder.Entity("codegather.Domain.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MetricsId")
                        .IsUnique();

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("Submissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Quis facilis quia esse nihil distinctio maiores voluptates. Voluptates voluptas non. Sunt a odio eligendi aut omnis quia distinctio omnis ut. Asperiores atque eum quis repudiandae doloribus commodi omnis dolorem velit. Voluptas molestias est. Sint ullam maxime sed id et facilis quasi esse.",
                            CreatedTime = new DateTime(2024, 2, 11, 14, 44, 57, 400, DateTimeKind.Local).AddTicks(8163),
                            IsDeleted = false,
                            MetricsId = 1,
                            QuestionId = 1,
                            SubmissionTime = new DateTime(2024, 2, 11, 14, 44, 57, 400, DateTimeKind.Local).AddTicks(8435),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "Quia soluta quam iste voluptatem quos. Adipisci qui doloribus sed possimus nulla perferendis quidem. Neque distinctio mollitia nihil omnis et voluptatem.",
                            CreatedTime = new DateTime(2024, 2, 11, 14, 44, 57, 400, DateTimeKind.Local).AddTicks(8439),
                            IsDeleted = false,
                            MetricsId = 2,
                            QuestionId = 1,
                            SubmissionTime = new DateTime(2024, 2, 11, 14, 44, 57, 400, DateTimeKind.Local).AddTicks(8608),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "Ea nam ullam qui rerum. Rerum reiciendis ut esse similique necessitatibus quo officia cumque quia. Est qui ipsa quae. Quia placeat voluptatem veniam saepe et sint officia nemo. Totam laborum ratione optio. Architecto temporibus tenetur dolores corrupti magni.",
                            CreatedTime = new DateTime(2024, 2, 11, 14, 44, 57, 400, DateTimeKind.Local).AddTicks(8611),
                            IsDeleted = false,
                            MetricsId = 3,
                            QuestionId = 2,
                            SubmissionTime = new DateTime(2024, 2, 11, 14, 44, 57, 400, DateTimeKind.Local).AddTicks(8878),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "Quidem et animi vitae quia aliquam. Sapiente illum ratione et nihil eius cumque ad sint quia. Consequatur exercitationem laborum adipisci consequatur laboriosam neque rerum optio id. Numquam cum eos ut quia quae consequatur repudiandae. Quae voluptate accusamus qui est minima voluptatum.",
                            CreatedTime = new DateTime(2024, 2, 11, 14, 44, 57, 400, DateTimeKind.Local).AddTicks(8881),
                            IsDeleted = false,
                            MetricsId = 4,
                            QuestionId = 2,
                            SubmissionTime = new DateTime(2024, 2, 11, 14, 44, 57, 400, DateTimeKind.Local).AddTicks(9035),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("codegather.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2024, 2, 11, 14, 44, 57, 401, DateTimeKind.Local).AddTicks(3189),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2024, 2, 11, 14, 44, 57, 401, DateTimeKind.Local).AddTicks(3207),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("codegather.Domain.Question", b =>
                {
                    b.HasOne("codegather.Domain.Competition", "Competition")
                        .WithMany("Questions")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("codegather.Domain.Submission", b =>
                {
                    b.HasOne("codegather.Domain.Metrics", "Metrics")
                        .WithOne()
                        .HasForeignKey("codegather.Domain.Submission", "MetricsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("codegather.Domain.Question", "Question")
                        .WithMany("Submissions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("codegather.Domain.User", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metrics");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("codegather.Domain.Competition", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("codegather.Domain.Question", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("codegather.Domain.User", b =>
                {
                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
