// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using codegather.Persistance;

#nullable disable

namespace codegather.Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("codegather.Domain.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Competitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2024, 2, 27, 17, 56, 8, 77, DateTimeKind.Local).AddTicks(8385),
                            Description = "Consequatur aliquid sunt temporibus tenetur omnis voluptatem quasi natus. Dolorum eius inventore rerum soluta rerum provident beatae commodi. Accusantium est ut eos rerum doloremque libero modi aut. Et dolore possimus excepturi et quia. Hic illo voluptatem id exercitationem.",
                            EndTime = new DateTime(2024, 3, 5, 17, 56, 8, 77, DateTimeKind.Local).AddTicks(8796),
                            IsDeleted = false,
                            StartTime = new DateTime(2024, 2, 27, 17, 56, 8, 77, DateTimeKind.Local).AddTicks(8792),
                            Title = "Vero repellendus."
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2024, 2, 27, 17, 56, 8, 77, DateTimeKind.Local).AddTicks(8804),
                            Description = "Eligendi qui illo optio nulla quis. Aliquam soluta odit aspernatur autem et. Aut aut possimus est labore quidem quas porro id cupiditate. Facilis quidem error laboriosam error eius voluptate. Necessitatibus veniam asperiores ut.",
                            EndTime = new DateTime(2024, 3, 5, 17, 56, 8, 77, DateTimeKind.Local).AddTicks(8999),
                            IsDeleted = false,
                            StartTime = new DateTime(2024, 2, 27, 17, 56, 8, 77, DateTimeKind.Local).AddTicks(8997),
                            Title = "Alias fuga."
                        });
                });

            modelBuilder.Entity("codegather.Domain.Metrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CompileTime")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<float>("MemoryUsage")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Metrics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompileTime = 0.5f,
                            CreatedTime = new DateTime(2024, 2, 27, 17, 56, 8, 80, DateTimeKind.Local).AddTicks(5478),
                            IsDeleted = false,
                            MemoryUsage = 0.5f
                        },
                        new
                        {
                            Id = 2,
                            CompileTime = 0.5f,
                            CreatedTime = new DateTime(2024, 2, 27, 17, 56, 8, 80, DateTimeKind.Local).AddTicks(5519),
                            IsDeleted = false,
                            MemoryUsage = 0.5f
                        },
                        new
                        {
                            Id = 3,
                            CompileTime = 0.5f,
                            CreatedTime = new DateTime(2024, 2, 27, 17, 56, 8, 80, DateTimeKind.Local).AddTicks(5522),
                            IsDeleted = false,
                            MemoryUsage = 0.5f
                        },
                        new
                        {
                            Id = 4,
                            CompileTime = 0.5f,
                            CreatedTime = new DateTime(2024, 2, 27, 17, 56, 8, 80, DateTimeKind.Local).AddTicks(5524),
                            IsDeleted = false,
                            MemoryUsage = 0.5f
                        });
                });

            modelBuilder.Entity("codegather.Domain.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestCases")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompetitionId = 1,
                            CreatedTime = new DateTime(2024, 2, 27, 17, 56, 8, 84, DateTimeKind.Local).AddTicks(1428),
                            Description = "Earum harum molestias voluptates est ad non. Harum qui totam laudantium sit quas eum molestiae rerum. Porro delectus vitae. Quia vitae esse qui rerum. Quia enim id numquam quo dicta reiciendis. Dolorem consequatur illum accusantium et aliquid perspiciatis.",
                            IsDeleted = false,
                            TestCases = "Test case 1, Test case 2, Test case 3"
                        },
                        new
                        {
                            Id = 2,
                            CompetitionId = 1,
                            CreatedTime = new DateTime(2024, 2, 27, 17, 56, 8, 84, DateTimeKind.Local).AddTicks(1837),
                            Description = "Rerum qui modi cum atque aut. Numquam quod magnam enim neque saepe. Consequuntur voluptatem commodi maiores animi reiciendis. Fugiat aut ipsum architecto qui fugiat et.",
                            IsDeleted = false,
                            TestCases = "Test case 1, Test case 2, Test case 3"
                        },
                        new
                        {
                            Id = 3,
                            CompetitionId = 2,
                            CreatedTime = new DateTime(2024, 2, 27, 17, 56, 8, 84, DateTimeKind.Local).AddTicks(1950),
                            Description = "Cupiditate temporibus assumenda minima officia eveniet eum quis. Itaque iure unde rerum est doloremque. Repellendus omnis consectetur magnam eum ratione molestiae est. Corrupti ut voluptas.",
                            IsDeleted = false,
                            TestCases = "Test case 1, Test case 2, Test case 3"
                        },
                        new
                        {
                            Id = 4,
                            CompetitionId = 2,
                            CreatedTime = new DateTime(2024, 2, 27, 17, 56, 8, 84, DateTimeKind.Local).AddTicks(2100),
                            Description = "Suscipit consequatur necessitatibus. Illum enim inventore at voluptatem distinctio. Sit sint odit.",
                            IsDeleted = false,
                            TestCases = "Test case 1, Test case 2, Test case 3"
                        });
                });

            modelBuilder.Entity("codegather.Domain.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MetricsId")
                        .IsUnique();

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("Submissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Consequatur tenetur eum est veniam corporis labore pariatur voluptatum ut. Quod quo assumenda cumque. Qui laboriosam vero eligendi in. Soluta unde aut recusandae.",
                            CreatedTime = new DateTime(2024, 2, 27, 17, 56, 8, 87, DateTimeKind.Local).AddTicks(1490),
                            IsCorrect = true,
                            IsDeleted = false,
                            MetricsId = 1,
                            QuestionId = 1,
                            SubmissionTime = new DateTime(2024, 2, 27, 17, 56, 8, 87, DateTimeKind.Local).AddTicks(1759),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "Molestiae ut deleniti quibusdam. Unde labore ut culpa quisquam eveniet quibusdam quia delectus. Cum ad voluptas voluptates sit perferendis. Quam possimus repellendus. Accusamus est in ipsum. Aperiam quis quia distinctio in facilis dolores quis error ea.",
                            CreatedTime = new DateTime(2024, 2, 27, 17, 56, 8, 87, DateTimeKind.Local).AddTicks(1763),
                            IsCorrect = true,
                            IsDeleted = false,
                            MetricsId = 2,
                            QuestionId = 1,
                            SubmissionTime = new DateTime(2024, 2, 27, 17, 56, 8, 87, DateTimeKind.Local).AddTicks(1913),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "Voluptatem voluptatum quae delectus veniam illo optio. Eligendi accusantium ab magnam quisquam mollitia sequi quas. Aut perspiciatis eum nihil doloremque. Blanditiis vero rerum. Voluptate perspiciatis veritatis est aut.",
                            CreatedTime = new DateTime(2024, 2, 27, 17, 56, 8, 87, DateTimeKind.Local).AddTicks(1916),
                            IsCorrect = true,
                            IsDeleted = false,
                            MetricsId = 3,
                            QuestionId = 2,
                            SubmissionTime = new DateTime(2024, 2, 27, 17, 56, 8, 87, DateTimeKind.Local).AddTicks(2141),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "Non nihil ex voluptas quam odio porro fugit. Corporis rerum sed rerum fugit est laudantium aperiam impedit exercitationem. Ut non quo minus architecto rerum aspernatur nulla facilis. Consectetur perspiciatis eos. Ab sit et voluptatibus itaque vitae cumque possimus iste.",
                            CreatedTime = new DateTime(2024, 2, 27, 17, 56, 8, 87, DateTimeKind.Local).AddTicks(2145),
                            IsCorrect = false,
                            IsDeleted = false,
                            MetricsId = 4,
                            QuestionId = 2,
                            SubmissionTime = new DateTime(2024, 2, 27, 17, 56, 8, 87, DateTimeKind.Local).AddTicks(2335),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("codegather.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2024, 2, 27, 17, 56, 8, 87, DateTimeKind.Local).AddTicks(8333),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2024, 2, 27, 17, 56, 8, 87, DateTimeKind.Local).AddTicks(8352),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("codegather.Domain.Question", b =>
                {
                    b.HasOne("codegather.Domain.Competition", "Competition")
                        .WithMany("Questions")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("codegather.Domain.Submission", b =>
                {
                    b.HasOne("codegather.Domain.Metrics", "Metrics")
                        .WithOne()
                        .HasForeignKey("codegather.Domain.Submission", "MetricsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("codegather.Domain.Question", "Question")
                        .WithMany("Submissions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("codegather.Domain.User", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metrics");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("codegather.Domain.Competition", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("codegather.Domain.Question", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("codegather.Domain.User", b =>
                {
                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
