// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using codegather.Persistance;

#nullable disable

namespace codegather.Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("codegather.Domain.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Competitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2024, 2, 10, 21, 34, 1, 889, DateTimeKind.Local).AddTicks(1019),
                            Description = "Totam rem nobis eum enim ab. Velit ab architecto qui sequi sed consequatur quidem. Et quo qui saepe nobis facere ea ut. Dicta blanditiis voluptas veniam temporibus est. Saepe molestias et officia consequatur nostrum repudiandae. Eos excepturi assumenda ipsum repellendus.",
                            EndTime = new DateTime(2024, 2, 17, 21, 34, 1, 889, DateTimeKind.Local).AddTicks(1372),
                            IsDeleted = false,
                            StartTime = new DateTime(2024, 2, 10, 21, 34, 1, 889, DateTimeKind.Local).AddTicks(1369),
                            Title = "Et quis."
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2024, 2, 10, 21, 34, 1, 889, DateTimeKind.Local).AddTicks(1379),
                            Description = "Natus ratione ipsa error voluptates et ea quidem nisi. Et eum necessitatibus. Dolores expedita dolorum occaecati sunt est soluta vel voluptates. Deserunt quia ea ipsam rerum voluptates possimus quibusdam. Voluptas sit dicta animi nemo laudantium debitis non ea dolores.",
                            EndTime = new DateTime(2024, 2, 17, 21, 34, 1, 889, DateTimeKind.Local).AddTicks(1594),
                            IsDeleted = false,
                            StartTime = new DateTime(2024, 2, 10, 21, 34, 1, 889, DateTimeKind.Local).AddTicks(1592),
                            Title = "Impedit nobis."
                        });
                });

            modelBuilder.Entity("codegather.Domain.Metrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CompileTime")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<float>("MemoryUsage")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Metrics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompileTime = 0.5f,
                            CreatedTime = new DateTime(2024, 2, 10, 21, 34, 1, 891, DateTimeKind.Local).AddTicks(4486),
                            IsDeleted = false,
                            MemoryUsage = 0.5f
                        },
                        new
                        {
                            Id = 2,
                            CompileTime = 0.5f,
                            CreatedTime = new DateTime(2024, 2, 10, 21, 34, 1, 891, DateTimeKind.Local).AddTicks(4508),
                            IsDeleted = false,
                            MemoryUsage = 0.5f
                        },
                        new
                        {
                            Id = 3,
                            CompileTime = 0.5f,
                            CreatedTime = new DateTime(2024, 2, 10, 21, 34, 1, 891, DateTimeKind.Local).AddTicks(4511),
                            IsDeleted = false,
                            MemoryUsage = 0.5f
                        },
                        new
                        {
                            Id = 4,
                            CompileTime = 0.5f,
                            CreatedTime = new DateTime(2024, 2, 10, 21, 34, 1, 891, DateTimeKind.Local).AddTicks(4513),
                            IsDeleted = false,
                            MemoryUsage = 0.5f
                        });
                });

            modelBuilder.Entity("codegather.Domain.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestCases")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompetitionId = 1,
                            CreatedTime = new DateTime(2024, 2, 10, 21, 34, 1, 893, DateTimeKind.Local).AddTicks(6891),
                            Description = "Suscipit sit quia non quidem. Et consequatur repellat explicabo reiciendis. Adipisci quisquam consequatur voluptas incidunt officia autem natus dolore voluptatem.",
                            IsDeleted = false,
                            TestCases = "Test case 1, Test case 2, Test case 3"
                        },
                        new
                        {
                            Id = 2,
                            CompetitionId = 1,
                            CreatedTime = new DateTime(2024, 2, 10, 21, 34, 1, 893, DateTimeKind.Local).AddTicks(7086),
                            Description = "Suscipit dicta dolorem alias sint non. Qui exercitationem voluptas tempore doloremque veniam quisquam quasi. Dolor dolores maxime rerum. Tempore harum minima aut vel ab sapiente veritatis.",
                            IsDeleted = false,
                            TestCases = "Test case 1, Test case 2, Test case 3"
                        },
                        new
                        {
                            Id = 3,
                            CompetitionId = 2,
                            CreatedTime = new DateTime(2024, 2, 10, 21, 34, 1, 893, DateTimeKind.Local).AddTicks(7240),
                            Description = "Illo et impedit nisi est. Id veritatis et voluptatum debitis qui vel aperiam sapiente maxime. Pariatur omnis repellendus eos possimus fuga a reiciendis rem sint. Cum voluptas iusto sed. Provident delectus velit occaecati in deserunt cupiditate.",
                            IsDeleted = false,
                            TestCases = "Test case 1, Test case 2, Test case 3"
                        },
                        new
                        {
                            Id = 4,
                            CompetitionId = 2,
                            CreatedTime = new DateTime(2024, 2, 10, 21, 34, 1, 893, DateTimeKind.Local).AddTicks(7391),
                            Description = "Et illo nihil corrupti hic deserunt. Architecto fuga ipsa quia excepturi fugit ut at praesentium in. Officia rerum nisi suscipit sint. Vel est eos rem praesentium impedit exercitationem. Voluptate eaque provident nam animi aut.",
                            IsDeleted = false,
                            TestCases = "Test case 1, Test case 2, Test case 3"
                        });
                });

            modelBuilder.Entity("codegather.Domain.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MetricsId")
                        .IsUnique();

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("Submissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Occaecati aliquam quasi neque vel. Expedita aliquid vitae optio et natus. Dolor qui voluptas alias velit veniam aspernatur sit ut. Quis eaque laborum.",
                            CreatedTime = new DateTime(2024, 2, 10, 21, 34, 1, 896, DateTimeKind.Local).AddTicks(8084),
                            IsDeleted = false,
                            MetricsId = 1,
                            QuestionId = 1,
                            SubmissionTime = new DateTime(2024, 2, 10, 21, 34, 1, 896, DateTimeKind.Local).AddTicks(8321),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "Incidunt dolor impedit aut voluptates qui fuga. Suscipit facilis voluptatem architecto aut reiciendis. Optio consequatur impedit mollitia consequatur consequatur modi cumque sunt. Perferendis eligendi non sit impedit neque eius suscipit. Eius aperiam et dolores ab sapiente porro odit unde.",
                            CreatedTime = new DateTime(2024, 2, 10, 21, 34, 1, 896, DateTimeKind.Local).AddTicks(8325),
                            IsDeleted = false,
                            MetricsId = 2,
                            QuestionId = 1,
                            SubmissionTime = new DateTime(2024, 2, 10, 21, 34, 1, 896, DateTimeKind.Local).AddTicks(8474),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "Omnis doloremque dicta amet fuga minima sit alias reprehenderit. Maxime accusamus id maxime qui. Officiis quia voluptatem aut et harum eveniet. Necessitatibus sequi doloribus ut facilis minus.",
                            CreatedTime = new DateTime(2024, 2, 10, 21, 34, 1, 896, DateTimeKind.Local).AddTicks(8477),
                            IsDeleted = false,
                            MetricsId = 3,
                            QuestionId = 2,
                            SubmissionTime = new DateTime(2024, 2, 10, 21, 34, 1, 896, DateTimeKind.Local).AddTicks(8622),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "Iure consequatur accusamus et delectus aspernatur delectus et corrupti. Tenetur dicta sed ipsum sed sed. Debitis cumque unde.",
                            CreatedTime = new DateTime(2024, 2, 10, 21, 34, 1, 896, DateTimeKind.Local).AddTicks(8625),
                            IsDeleted = false,
                            MetricsId = 4,
                            QuestionId = 2,
                            SubmissionTime = new DateTime(2024, 2, 10, 21, 34, 1, 896, DateTimeKind.Local).AddTicks(8753),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("codegather.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2024, 2, 10, 21, 34, 1, 897, DateTimeKind.Local).AddTicks(1056),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2024, 2, 10, 21, 34, 1, 897, DateTimeKind.Local).AddTicks(1112),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("codegather.Domain.Question", b =>
                {
                    b.HasOne("codegather.Domain.Competition", "Competition")
                        .WithMany("Questions")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("codegather.Domain.Submission", b =>
                {
                    b.HasOne("codegather.Domain.Metrics", "Metrics")
                        .WithOne()
                        .HasForeignKey("codegather.Domain.Submission", "MetricsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("codegather.Domain.Question", "Question")
                        .WithMany("Submissions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("codegather.Domain.User", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metrics");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("codegather.Domain.Competition", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("codegather.Domain.Question", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("codegather.Domain.User", b =>
                {
                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
